[profile.default]
solc_version = "0.8.17"
script = 'script'
test = 'test'
extra_output = ['storageLayout']
evm_version = "london"
fs_permissions=[
  {access="read", path="./out"},
  {access="read", path= "./script/config" },
  {access="read-write", path="./cache"},
]
allow_paths = ["../.."]
auto_detect_remappings = false
libs = ["lib"]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
polygon = "https://polygon-rpc.com"
optimism = "https://rpc.ankr.com/optimism"
arbitrum = "https://arb1.arbitrum.io/rpc"
linea = "https://rpc.linea.build"
ethereum = "https://rpc.ankr.com/eth"
blast = "https://rpc.blast.io"
