[profile.default]
solc_version = "0.8.24"
script = 'script'
test = 'test'
extra_output = ['storageLayout']
evm_version = "london"
fs_permissions=[
  {access="read", path="./out"},
  {access="read", path= "./script/config" },
  {access="read", path= "./sphinx.lock" },
  {access="read-write", path="./cache"},
]
allow_paths = ["../.."]
auto_detect_remappings = false
libs = ["lib"]

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
linea = "https://rpc.linea.build"
ethereum = "https://eth.llamarpc.com"
blast = "https://rpc.blast.io"
polygon-zkevm = "https://zkevm-rpc.com"
darwinia = "https://darwinia-rpc.itering.io"
base = "https://mainnet.base.org"
gnosis = "https://rpc.gnosischain.com"
mantle = "https://rpc.mantle.xyz"
moonbeam = "https://rpc.api.moonbeam.network"
astar-zkevm = "https://rpc-zkevm.astar.network"
crab = "https://crab-rpc.darwinia.network"
scroll = "https://rpc.scroll.io"
avalanche = "https://avalanche.drpc.org"
polygon-pos = "https://polygon.drpc.org"
optimistic = "https://optimism.drpc.org"
arbitrum = "https://arbitrum.drpc.org"
bnb = "https://bsc.drpc.org"
zircuit = "https://zircuit1-mainnet.p2pify.com"
morph = "https://rpc.morphl2.io"
